In [1]:
from datetime import datetime, timedelta
import math

import numpy as np
import pandas as pd
import requests
import yfinance as yf

In [2]:
sp500 = pd.read_csv('../data/flat-ui__data-MonJun102024.csv')

In [3]:
sp500

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,A,Agilent Technologies,Health Care,Life Sciences Tools & Services,"Santa Clara, California",2000-06-05,1090872,1999
1,AAL,American Airlines Group,Industrials,Passenger Airlines,"Fort Worth, Texas",2015-03-23,6201,1934
2,AAPL,Apple Inc.,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193,1977
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ABNB,Airbnb,Consumer Discretionary,"Hotels, Resorts & Cruise Lines","San Francisco, California",2023-09-18,1559720,2008
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
501,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [4]:
sp500['Symbol'] = sp500['Symbol'].str.replace('.', '-')
symbols_list = sp500['Symbol'].unique().tolist()
symbols_list

['A',
 'AAL',
 'AAPL',
 'ABBV',
 'ABNB',
 'ABT',
 'ACGL',
 'ACN',
 'ADBE',
 'ADI',
 'ADM',
 'ADP',
 'ADSK',
 'AEE',
 'AEP',
 'AES',
 'AFL',
 'AIG',
 'AIZ',
 'AJG',
 'AKAM',
 'ALB',
 'ALGN',
 'ALL',
 'ALLE',
 'AMAT',
 'AMCR',
 'AMD',
 'AME',
 'AMGN',
 'AMP',
 'AMT',
 'AMZN',
 'ANET',
 'ANSS',
 'AON',
 'AOS',
 'APA',
 'APD',
 'APH',
 'APTV',
 'ARE',
 'ATO',
 'AVB',
 'AVGO',
 'AVY',
 'AWK',
 'AXON',
 'AXP',
 'AZO',
 'BA',
 'BAC',
 'BALL',
 'BAX',
 'BBWI',
 'BBY',
 'BDX',
 'BEN',
 'BF-B',
 'BG',
 'BIIB',
 'BIO',
 'BK',
 'BKNG',
 'BKR',
 'BLDR',
 'BLK',
 'BMY',
 'BR',
 'BRK-B',
 'BRO',
 'BSX',
 'BWA',
 'BX',
 'BXP',
 'C',
 'CAG',
 'CAH',
 'CARR',
 'CAT',
 'CB',
 'CBOE',
 'CBRE',
 'CCI',
 'CCL',
 'CDNS',
 'CDW',
 'CE',
 'CEG',
 'CF',
 'CFG',
 'CHD',
 'CHRW',
 'CHTR',
 'CI',
 'CINF',
 'CL',
 'CLX',
 'CMA',
 'CMCSA',
 'CME',
 'CMG',
 'CMI',
 'CMS',
 'CNC',
 'CNP',
 'COF',
 'COO',
 'COP',
 'COR',
 'COST',
 'CPB',
 'CPRT',
 'CPT',
 'CRL',
 'CRM',
 'CSCO',
 'CSGP',
 'CSX',
 'CTAS',
 'CTLT',
 'CTRA',
 'CTSH',
 'CTVA',
 'CVS',
 'CVX',
 'CZR',
 'D',
 'DAL',
 'DAY',
 'DD',
 'DE',
 'DECK',
 'DFS',
 'DG',
 'DGX',
 'DHI',
 'DHR',
 'DIS',
 'DLR',
 'DLTR',
 'DOC',
 'DOV',
 'DOW',
 'DPZ',
 'DRI',
 'DTE',
 'DUK',
 'DVA',
 'DVN',
 'DXCM',
 'EA',
 'EBAY',
 'ECL',
 'ED',
 'EFX',
 'EG',
 'EIX',
 'EL',
 'ELV',
 'EMN',
 'EMR',
 'ENPH',
 'EOG',
 'EPAM',
 'EQIX',
 'EQR',
 'EQT',
 'ES',
 'ESS',
 'ETN',
 'ETR',
 'ETSY',
 'EVRG',
 'EW',
 'EXC',
 'EXPD',
 'EXPE',
 'EXR',
 'F',
 'FANG',
 'FAST',
 'FCX',
 'FDS',
 'FDX',
 'FE',
 'FFIV',
 'FI',
 'FICO',
 'FIS',
 'FITB',
 'FLT',
 'FMC',
 'FOX',
 'FOXA',
 'FRT',
 'FSLR',
 'FTNT',
 'FTV',
 'GD',
 'GE',
 'GEHC',
 'GEN',
 'GILD',
 'GIS',
 'GL',
 'GLW',
 'GM',
 'GNRC',
 'GOOG',
 'GOOGL',
 'GPC',
 'GPN',
 'GRMN',
 'GS',
 'GWW',
 'HAL',
 'HAS',
 'HBAN',
 'HCA',
 'HD',
 'HES',
 'HIG',
 'HII',
 'HLT',
 'HOLX',
 'HON',
 'HPE',
 'HPQ',
 'HRL',
 'HSIC',
 'HST',
 'HSY',
 'HUBB',
 'HUM',
 'HWM',
 'IBM',
 'ICE',
 'IDXX',
 'IEX',
 'IFF',
 'ILMN',
 'INCY',
 'INTC',
 'INTU',
 'INVH',
 'IP',
 'IPG',
 'IQV',
 'IR',
 'IRM',
 'ISRG',
 'IT',
 'ITW',
 'IVZ',
 'J',
 'JBHT',
 'JBL',
 'JCI',
 'JKHY',
 'JNJ',
 'JNPR',
 'JPM',
 'K',
 'KDP',
 'KEY',
 'KEYS',
 'KHC',
 'KIM',
 'KLAC',
 'KMB',
 'KMI',
 'KMX',
 'KO',
 'KR',
 'KVUE',
 'L',
 'LDOS',
 'LEN',
 'LH',
 'LHX',
 'LIN',
 'LKQ',
 'LLY',
 'LMT',
 'LNT',
 'LOW',
 'LRCX',
 'LULU',
 'LUV',
 'LVS',
 'LW',
 'LYB',
 'LYV',
 'MA',
 'MAA',
 'MAR',
 'MAS',
 'MCD',
 'MCHP',
 'MCK',
 'MCO',
 'MDLZ',
 'MDT',
 'MET',
 'META',
 'MGM',
 'MHK',
 'MKC',
 'MKTX',
 'MLM',
 'MMC',
 'MMM',
 'MNST',
 'MO',
 'MOH',
 'MOS',
 'MPC',
 'MPWR',
 'MRK',
 'MRNA',
 'MRO',
 'MS',
 'MSCI',
 'MSFT',
 'MSI',
 'MTB',
 'MTCH',
 'MTD',
 'MU',
 'NCLH',
 'NDAQ',
 'NDSN',
 'NEE',
 'NEM',
 'NFLX',
 'NI',
 'NKE',
 'NOC',
 'NOW',
 'NRG',
 'NSC',
 'NTAP',
 'NTRS',
 'NUE',
 'NVDA',
 'NVR',
 'NWS',
 'NWSA',
 'NXPI',
 'O',
 'ODFL',
 'OKE',
 'OMC',
 'ON',
 'ORCL',
 'ORLY',
 'OTIS',
 'OXY',
 'PANW',
 'PARA',
 'PAYC',
 'PAYX',
 'PCAR',
 'PCG',
 'PEG',
 'PEP',
 'PFE',
 'PFG',
 'PG',
 'PGR',
 'PH',
 'PHM',
 'PKG',
 'PLD',
 'PM',
 'PNC',
 'PNR',
 'PNW',
 'PODD',
 'POOL',
 'PPG',
 'PPL',
 'PRU',
 'PSA',
 'PSX',
 'PTC',
 'PWR',
 'PXD',
 'PYPL',
 'QCOM',
 'QRVO',
 'RCL',
 'REG',
 'REGN',
 'RF',
 'RHI',
 'RJF',
 'RL',
 'RMD',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RSG',
 'RTX',
 'RVTY',
 'SBAC',
 'SBUX',
 'SCHW',
 'SHW',
 'SJM',
 'SLB',
 'SMCI',
 'SNA',
 'SNPS',
 'SO',
 'SPG',
 'SPGI',
 'SRE',
 'STE',
 'STLD',
 'STT',
 'STX',
 'STZ',
 'SWK',
 'SWKS',
 'SYF',
 'SYK',
 'SYY',
 'T',
 'TAP',
 'TDG',
 'TDY',
 'TECH',
 'TEL',
 'TER',
 'TFC',
 'TFX',
 'TGT',
 'TJX',
 'TMO',
 'TMUS',
 'TPR',
 'TRGP',
 'TRMB',
 'TROW',
 'TRV',
 'TSCO',
 'TSLA',
 'TSN',
 'TT',
 'TTWO',
 'TXN',
 'TXT',
 'TYL',
 'UAL',
 'UBER',
 'UDR',
 'UHS',
 'ULTA',
 'UNH',
 'UNP',
 'UPS',
 'URI',
 'USB',
 'V',
 'VFC',
 'VICI',
 'VLO',
 'VLTO',
 'VMC',
 'VRSK',
 'VRSN',
 'VRTX',
 'VTR',
 'VTRS',
 'VZ',
 'WAB',
 'WAT',
 'WBA',
 'WBD',
 'WDC',
 'WEC',
 'WELL',
 'WFC',
 'WM',
 'WMB',
 'WMT',
 'WRB',
 'WRK',
 'WST',
 'WTW',
 'WY',
 'WYNN',
 'XEL',
 'XOM',
 'XRAY',
 'XYL',
 'YUM',
 'ZBH',
 'ZBRA',
 'ZTS']

In [5]:
tickers = []
for ticker in symbols_list:
    try:
        ticker_info = yf.Ticker(ticker).info
        if 'marketCap' in ticker_info and ticker_info['marketCap'] is not None:
            tickers.append(ticker)
        else:
            print(f"No valid market cap data for {ticker}")
    except Exception as e:
        print(f"Ticker {ticker} is invalid or delisted: {e}")

404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/FLT?modules=financialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&corsDomain=finance.yahoo.com&formatted=false&symbol=FLT&crumb=R1oLG%2FEpXV4

No valid market cap data for FLT

In [6]:
end_date = datetime.now() - timedelta(days=3)
end_date_pd = pd.to_datetime(end_date)

In [7]:
start_date = end_date_pd - pd.DateOffset(years=2)
start_date

Timestamp('2022-06-07 23:05:43.199784')

In [8]:
df = yf.download(tickers=tickers, start=start_date, end=end_date_pd)
df = df.dropna()
df

[*********************100%%**********************]  502 of 502 completed

Price        Adj Close                                                         \
Ticker               A    AAL        AAPL        ABBV        ABNB         ABT
Date
2023-10-04  111.669998  12.73  173.660004  147.690002  127.410004   95.650002
2023-10-05  110.349998  12.85  174.910004  147.449997  124.989998   96.199997
2023-10-06  110.639999  12.76  177.490005  148.240005  126.360001   96.879997
2023-10-09  111.279999  12.24  178.990005  149.110001  127.769997   96.760002
2023-10-10  113.290001  12.26  178.389999  148.889999  131.589996   97.559998
...                ...    ...         ...         ...         ...         ...
2024-04-26  137.740005  13.88  169.300003  159.619995  164.229996  107.529999
2024-04-29  139.589996  13.98  173.500000  161.520004  162.250000  107.269997
2024-04-30  137.039993  13.51  170.330002  162.639999  158.570007  105.970001
2024-05-01  138.690002  13.58  169.300003  161.720001  156.160004  106.290001
2024-05-02  137.520004  13.86  173.029999  160.809998  158.330002  105.919998

Price                                                      ...   Volume  \
Ticker           ACGL         ACN        ADBE         ADI  ...       WY
Date                                                       ...
2023-10-04  80.459999  309.390015  518.419983  173.789993  ...  3954000
2023-10-05  81.639999  309.660004  516.440002  172.100006  ...  3724500
2023-10-06  82.180000  312.190002  526.679993  173.970001  ...  4318300
2023-10-09  82.070000  312.010010  529.289978  173.320007  ...  3171800
2023-10-10  81.860001  312.320007  532.719971  175.970001  ...  3078500
...               ...         ...         ...         ...  ...      ...
2024-04-26  90.900002  308.010010  477.559998  201.970001  ...  3616700
2024-04-29  91.250000  303.160004  473.070007  203.899994  ...  2837700
2024-04-30  93.540001  300.910004  462.829987  200.610001  ...  4876300
2024-05-01  95.800003  298.660004  469.390015  193.889999  ...  4225200
2024-05-02  95.169998  300.339996  476.570007  196.490005  ...  4710500

Price                                                                       \
Ticker         WYNN      XEL       XOM     XRAY      XYL      YUM      ZBH
Date
2023-10-04  2289300  3948700  19622200  4840000  1614400  1381200  1597600
2023-10-05  1513600  3835400  20128800  3136800  1131000  1240200  1048200
2023-10-06  2470600  6337200  25363400  2164600  1149700  2111900  1570500
2023-10-09  1622800  2702100  22369900  1377500   949500  1840000   865900
2023-10-10  1674800  3117900  13892000  1611600  1478800  1643300   999400
...             ...      ...       ...      ...      ...      ...      ...
2024-04-26  1420000  6451700  27289500  1158500  1112300  2008100  1099200
2024-04-29  1588300  3884600  17309900  2209900  1277800  2221000  1195000
2024-04-30  2752900  6805600  21083300  2331800  1397800  4087300  1429000
2024-05-01  1846900  4589600  27777700  2453300  1773900  4639900  2710500
2024-05-02  1873200  3910500  25513600  6670400  2784800  2425400  2931700

Price
Ticker        ZBRA      ZTS
Date
2023-10-04  487500  1673400
2023-10-05  448400  2083200
2023-10-06  384000  1490600
2023-10-09  266600  1215100
2023-10-10  361900  1665300
...            ...      ...
2024-04-26  461400  5236500
2024-04-29  560700  4849500
2024-04-30  907700  3647900
2024-05-01  580100  3779100
2024-05-02  507800  5323100

[146 rows x 3012 columns]

In [9]:
df = df.stack(future_stack=True)
df.index.names = ['date', 'ticker']
df.columns = df.columns.str.lower()
df

Price               adj close       close        high         low        open  \
date       ticker
2023-10-04 A       111.669998  111.669998  111.889999  109.379997  110.410004
           AAL      12.730000   12.730000   12.820000   12.340000   12.400000
           AAPL    173.660004  173.660004  174.210007  170.970001  171.089996
           ABBV    147.690002  147.690002  148.080002  146.309998  146.570007
           ABNB    127.410004  127.410004  130.220001  127.294998  128.750000
...                       ...         ...         ...         ...         ...
2024-05-02 XYL     135.990005  135.990005  137.179993  132.020004  132.429993
           YUM     135.070007  135.070007  136.610001  134.759995  135.500000
           ZBH     118.459999  118.459999  123.959999  117.599998  121.989998
           ZBRA    312.709991  312.709991  315.170013  303.209991  312.230011
           ZTS     167.229996  167.229996  169.990005  161.380005  163.100006

Price                  volume
date       ticker
2023-10-04 A        1541700.0
           AAL     49738100.0
           AAPL    53020300.0
           ABBV     3159600.0
           ABNB     5822000.0
...                       ...
2024-05-02 XYL      2784800.0
           YUM      2425400.0
           ZBH      2931700.0
           ZBRA      507800.0
           ZTS      5323100.0

[73292 rows x 6 columns]